[build]
publish = "/public"

[context.production.environment]
  HUGO_VERSION = "0.69.2"
  command = "hugo server --gc -s . --minify -e 'production'"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.69.2"
  command = "hugo server --gc -s .  -e 'development'"
  

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL"